### ISSUE TITLE
Cannot import Dfinity package

### ISSUE THREAD

**Issue by MCLYang** [gabrielnic/dfinity-react#5]
I install the package by npm. When I try to` import { AuthClient } from '@dfinity/auth-client';` it returns the error like

`Failed to parse source map from 'F:\dfinity-react\node_modules\@dfinity\agent\src\actor.ts' file: Error: ENOENT: no such file or directory, open 'F:\dfinity-react\node_modules\@dfinity\agent\src\actor.ts'`

check the agent file, there is no 'src' indeed. Let me try me make a screen shot

![image](https://user-images.githubusercontent.com/46518089/148662386-1a3a4b10-776f-4fe9-b4fa-8924f2af8734.png)

Appreciate the help

**Comment by MCLYang** [comment]
Tried `yarn install` as well. Doesn't work neither

**Comment by gabrielnic** [comment]
hi, the sdk won't work on windows unfortunately if I'm seeing that right. 
I tried on my osx and all I had to do to make this work was to remove the yarn.lock file. 

Try and let me know

**Comment by MCLYang** [comment]
I tried on ubuntu 16.04 still still same error. Here is pure repo that you could reproduce the error: https://github.com/MCLYang/err_react
![image](https://user-images.githubusercontent.com/46518089/149021100-0f5f5598-cf08-4853-a3f8-174fe081dea9.png)

**Comment by gabrielnic** [comment]
it has to be Ubuntu 20 or more newer for some reason dfx has some issues with older version. I also pushed a fix for a craco issue and upgraded to 0.8.6. Let me know if it works for you.

**Comment by MCLYang** [comment]
I tried on on Ubuntu 20.04.3. still errors. Here is the rest config:

node v14.17.6
npm 6.14.15
yarn 1.22.15
dfx 0.8.4(0.8.6 seems not available from `sh -ci "$(curl -fsSL https://smartcontracts.org/install.sh)"`)

**Comment by gabrielnic** [comment]
I just tried with a fresh install of ubuntu 20: 
node -v v14.17.1
npm -v 6.14.13
yarn --version 1.22.4

You can specify the dfx version using this: https://smartcontracts.org/docs/developers-guide/cli-reference/dfx-envars.html#_dfx_version

It works very well for me. Make sure you update the git repo for II.

**Comment by ninegua** [comment]
Our SDK (dfx) actually can work on windows. You just need to make sure your project is created under WSL filesystem, not the Windows filesystem. Usually `cd $HOME` will let you go to your WSL filesystem, then you create a project over there. dfx will work fairly well.

**Comment by gabrielnic** [comment]
> Our SDK (dfx) actually can work on windows. You just need to make sure your project is created under WSL filesystem, not the Windows filesystem. Usually `cd $HOME` will let you go to your WSL filesystem, then you create a project over there. dfx will work fairly well.

Yeah, forgot to mention I'm using windows as well. WSL2 (not wsl1 cause it has some issues) ubuntu 20. I've been using it for almost 1 year now and it's been great. No issues at all.

**Comment by MCLYang** [comment]
It's very interesting that I switch from JS to TS then it works. Idk how but I would like to take a closer look later.
